version: '3.7'

services:
  pgadmin:
    env_file: .env
    # dpage/pgadmin4 is now the official release
    image: dpage/pgadmin4:latest
    ports:
      - "8123:80"
    volumes:
      # Session data, user files, config files, config database go here.
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # Added SCRIPT_NAME to solve this problem:
      #https://stackoverflow.com/questions/46381668/pgadmin4-wont-work-in-specific-location-behind-nginx
#      SCRIPT_NAME: /pgadmin4
#      NETWORK_ACCESS: internal
#     LETSENCRYPT_HOST: ${PGADMIN_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
volumes:
  pgadmin_data:
